"""Initial schema

Revision ID: initial_001
Revises:
Create Date: 2025-11-18 18:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'initial_001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playtomic_id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('operating_hours', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clubs_id'), 'clubs', ['id'], unique=False)
    op.create_index(op.f('ix_clubs_playtomic_id'), 'clubs', ['playtomic_id'], unique=True)
    op.create_index(op.f('ix_clubs_slug'), 'clubs', ['slug'], unique=True)

    op.create_table('courts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('playtomic_court_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sport_type', sa.String(), nullable=True),
    sa.Column('surface_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courts_club_id'), 'courts', ['club_id'], unique=False)
    op.create_index(op.f('ix_courts_id'), 'courts', ['id'], unique=False)

    op.create_table('monitoring_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('frequency_minutes', sa.Integer(), nullable=False),
    sa.Column('start_time_local', sa.Time(), nullable=True),
    sa.Column('end_time_local', sa.Time(), nullable=True),
    sa.Column('days_ahead', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id')
    )
    op.create_index(op.f('ix_monitoring_configs_club_id'), 'monitoring_configs', ['club_id'], unique=True)
    op.create_index(op.f('ix_monitoring_configs_id'), 'monitoring_configs', ['id'], unique=False)

    op.create_table('availability_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_snapshots_club_date', 'availability_snapshots', ['club_id', 'date'], unique=False)
    op.create_index('ix_snapshots_club_date_court', 'availability_snapshots', ['club_id', 'date', 'court_id'], unique=False)
    op.create_index('ix_snapshots_club_snapshot_time', 'availability_snapshots', ['club_id', 'snapshot_time'], unique=False)
    op.create_index(op.f('ix_availability_snapshots_club_id'), 'availability_snapshots', ['club_id'], unique=False)
    op.create_index(op.f('ix_availability_snapshots_court_id'), 'availability_snapshots', ['court_id'], unique=False)
    op.create_index(op.f('ix_availability_snapshots_date'), 'availability_snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_availability_snapshots_id'), 'availability_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_availability_snapshots_snapshot_time'), 'availability_snapshots', ['snapshot_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_availability_snapshots_snapshot_time'), table_name='availability_snapshots')
    op.drop_index(op.f('ix_availability_snapshots_id'), table_name='availability_snapshots')
    op.drop_index(op.f('ix_availability_snapshots_date'), table_name='availability_snapshots')
    op.drop_index(op.f('ix_availability_snapshots_court_id'), table_name='availability_snapshots')
    op.drop_index(op.f('ix_availability_snapshots_club_id'), table_name='availability_snapshots')
    op.drop_index('ix_snapshots_club_snapshot_time', table_name='availability_snapshots')
    op.drop_index('ix_snapshots_club_date_court', table_name='availability_snapshots')
    op.drop_index('ix_snapshots_club_date', table_name='availability_snapshots')
    op.drop_table('availability_snapshots')
    op.drop_index(op.f('ix_monitoring_configs_id'), table_name='monitoring_configs')
    op.drop_index(op.f('ix_monitoring_configs_club_id'), table_name='monitoring_configs')
    op.drop_table('monitoring_configs')
    op.drop_index(op.f('ix_courts_id'), table_name='courts')
    op.drop_index(op.f('ix_courts_club_id'), table_name='courts')
    op.drop_table('courts')
    op.drop_index(op.f('ix_clubs_slug'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_playtomic_id'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_id'), table_name='clubs')
    op.drop_table('clubs')
    # ### end Alembic commands ###
